config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :show, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, foreign_key: 'post_id'
  has_many :comments, foreign_key: 'post_id'

  validates :title, presence: true, length: { minimum: 1, maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def most_recent_comments
    comments.limit(5).order(created_at: :desc)
  end

  private

  def update_post_counter
    author.increment!(:post_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_post
    posts.limit(3).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @commment = Comment.new
    respond_to do |format|
      format.html { render :new, locals: { comment: @comment } }
    end
  end

  def create
    current_user = User.find(params[:user_id])
    post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post = post
    if @comment.save
      flash[:notice] = 'Comment has been created successfully'
      redirect_to user_post_path(current_user, post)
    else
      flash.now[:error] = "Error: Couldn't create comment"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    current_user = User.find(params[:user_id])
    post = Post.find(params[:post_id])
    @like = Like.new(user: current_user, post:)
    if @like.save
      flash[:success] = 'Like has been created successfully'
    else
      flash[:error] = 'Like not created'
    end
    redirect_to user_post_path(current_user, post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts or /posts.json
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: @user)
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    current_user = User.find(params[:user_id])
    @post = Post.new(post_params)
    @post.author = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      flash[:notice] = 'Post has been created successfully'
      redirect_to user_posts_path(current_user)
    else
      flash.now[:error] = "Error: Couldn't create post"
      render :new, status: :unprocessable_entity
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    @user = User.find(params[:user_id])
    @post = Post.find_by!(id: params[:id], author_id: params[:user_id])
  end

  private

  def post_params
    params.require(:new_post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users or /users.json
  def index
    @users = User.all
    render 'index'
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
    render 'show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
  <div >
    <h1>Add Comment</h1><br>
  </div>

<%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, scope: :comment do |form| %>

  <div >
    <%= form.label :text %><br>
    <%= form.text_area :text, rows: 5 %>
  </div>
  <div >
       <%= form.submit "Add Comment" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="post_main_container">
  <div>
    <%= render 'shared/user', user: @user%>
  </div>
  <h2>All User Posts</h2>
  <div id="posts">
    <% @posts.each do |post| %>
      <p>
        <div>
          <%= render 'shared/post', post: post%>
        </div>
        <div class="comments">
          <%post.most_recent_comments.each do |comment|%>
            <div class="user_comment">
              <p>User: <%=comment.author_id%></p>
              <p>Comment: <%=comment.text%></p>
            </div>
          <% end %>
        </div> 
      </p>
    <% end %>
</div>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :new_post do |form| %>
    <% if @post.errors.any? %>
<div style="color: red">
    <% @post.errors.full_messages.each do |message| %>
        <div> <%= message %> </div>
    <% end %>
</div>
<% end%>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :text %><br>
        <%= form.text_area :text, rows: "5" %>
    </div>

   <%= form.submit "Add Post" %>
<% end %>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <div>
    <div>
      <span><%=@post.title%> by <%=@user.name%></span>
      <p>Number of comments: <%=@post.comments_counter%> Number of likes: <%=@post.likes_counter%></p>
    </div>
    <p><%=@post.text%></p>
  </div>
  <div>
    <%@post.comments.each do |comment|%>
          <p><%=comment.text%></p>
    <% end %>
  </div>
</div>

app/views/shared/_post.html.erb
<div class="post_container">
  <h2><%= post.title %></h2>
  <div><%= post.text %></div>
  <div class="interaction">
   <div>Number of Comments<%=post.comments_counter%></div>
   <div>Number of Likes:<%=post.likes_counter%></div>
  </div>
  <p><%= link_to "view post",  user_post_path(@user, post)%></p>
</div>

app/views/shared/_user.html.erb
<div class="user_container">
  <div class="image"><img src="<%= user.photo %>" alt="profile_photo"></div>
  <div class="user">
    <h2><%= link_to user.name, user %></h2>
  <div class="post_counter">Number of Posts: <%= user.post_counter %></div>
  </div>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="main_container">
  <h1>All Users</h1>

  <div id="users" class="users">
    <% @users.each do |user| %>
      <%= render 'shared/user', user: user%>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="specific_user">
  <%= render 'shared/user', user: @user%>
  <div class="bio_section">
    <h2>Bio</h2>
    <%=@user.bio%>
  </div>
  <div class="post_section">
    <h2>User Posts</h2>
    <% @user.most_recent_post.each do |post| %>
      <%= render 'shared/post', post: post%>
    <% end %>
    <div>
      <button class='user_button'>
        <%= link_to 'See all posts', user_posts_path(@user) %>
      </button>
    </div>
  </div>
<div>